name: 'provider_pipeline'
version: '1.0.0'

profile: 'provider_pipeline'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:   
  - "target"
  - "dbt_packages"

seeds:
  provider_pipeline:
    +delimiter: ","
    +quote: '"'
    +escape: '"'

models:
  provider_pipeline:
